import { createUseStyles } from 'react-jss'
import { tokens } from '@/theme/tokens'

export const useSkeletonStyles = createUseStyles({
  pulse: {
    height: 14,
    borderRadius: tokens.radius.sm,
    background: `linear-gradient(90deg, ${tokens.color.bgMuted} 0%, ${tokens.color.border} 50%, ${tokens.color.bgMuted} 100%)`,
    backgroundSize: '200% 100%',
    animation: '$pulse 1.25s ease-in-out infinite',
  },
  width40: { width: '40%' },
  width42: { width: '42%' },
  width55: { width: '55%' },
  width68: { width: '68%' },
  width70: { width: '70%' },
  width76: { width: '76%' },
  width88: { width: '88%' },
  width92: { width: '92%' },
  width100: { width: '100%' },
  width110: { width: 110 },
  width120: { width: 120 },
  width170: { width: 170 },
  width220: { width: 220 },
  height11: { height: 11 },
  height16: { height: 16 },
  height26: { height: 26 },
  height32: { height: 32 },
  height34: { height: 34 },
  height36: { height: 36 },
  height38: { height: 38 },
  panelRoot: { display: 'grid', gap: tokens.space.md, padding: tokens.space.lg },
  panelChart: { height: 280 },
  chartSkeleton: {
    boxSizing: 'border-box',
    height: 380,
    minWidth: 0,
    padding: [tokens.space.md, tokens.space.sm, tokens.space.sm, tokens.space.md],
    display: 'grid',
    gridTemplateRows: '1fr auto',
    gap: tokens.space.sm,
    '@media (max-width: 720px)': { height: 330 },
  },
  chartSkeletonCompact: { height: 360, '@media (max-width: 720px)': { height: 320 } },
  chartPlot: {
    position: 'relative',
    overflow: 'hidden',
    borderLeft: `1px solid ${tokens.color.border}`,
    borderBottom: `1px solid ${tokens.color.border}`,
    background: `repeating-linear-gradient(to bottom, transparent 0, transparent 24%, ${tokens.color.border} 25%)`,
  },
  chartWave: {
    position: 'absolute',
    left: '5%',
    right: '4%',
    top: '34%',
    height: 4,
    borderRadius: 999,
    transform: 'rotate(-3deg)',
  },
  chartWaveSecond: {
    position: 'absolute',
    left: '18%',
    right: '10%',
    top: '60%',
    height: 4,
    borderRadius: 999,
    transform: 'rotate(4deg)',
  },
  chartTicks: { display: 'flex', justifyContent: 'space-between', gap: tokens.space.sm },
  stockPage: { display: 'grid', gap: tokens.space.md },
  stockTabs: { display: 'flex', gap: 2, flexWrap: 'wrap' },
  stockPanel: {
    padding: tokens.space.lg,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    display: 'grid',
    gap: tokens.space.md,
  },
  stockPanelHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: tokens.space.md, flexWrap: 'wrap' },
  stockControls: { display: 'flex', justifyContent: 'flex-end', gap: tokens.space.sm, flexWrap: 'wrap', marginLeft: 'auto' },
  stockChips: { display: 'flex', gap: tokens.space.xs, flexWrap: 'wrap' },
  skeletonTableCard: {
    minHeight: 250,
    padding: tokens.space.lg,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    display: 'grid',
    alignContent: 'start',
    gap: tokens.space.md,
  },
  skeletonTableToolbar: { display: 'flex', justifyContent: 'flex-end' },
  formPage: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(260px, .42fr)',
    gap: tokens.space.md,
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  },
  formCard: {
    minHeight: 300,
    padding: tokens.space.lg,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    display: 'grid',
    alignContent: 'start',
    gap: tokens.space.md,
  },
  investmentSummary: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: tokens.space.md,
  },
  dashboard: { display: 'grid', gap: tokens.space.lg },
  cards: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))', gap: tokens.space.md },
  card: {
    minHeight: 142,
    padding: tokens.space.md,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    display: 'grid',
    alignContent: 'start',
    gap: tokens.space.sm,
  },
  cardTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  icon: { width: 32, height: 32 },
  section: {
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    overflow: 'hidden',
  },
  sectionHead: {
    minHeight: 68,
    padding: tokens.space.lg,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: tokens.space.md,
    borderBottom: `1px solid ${tokens.color.border}`,
  },
  controlRow: { display: 'flex', gap: tokens.space.sm },
  sectionBody: {
    padding: tokens.space.lg,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.4fr) minmax(260px, .8fr)',
    gap: tokens.space.lg,
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  },
  graph: { height: 300 },
  tableRows: { display: 'grid', gap: tokens.space.sm, alignContent: 'start' },
  page: { display: 'grid', gap: tokens.space.md },
  toolbar: {
    height: 68,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    padding: tokens.space.md,
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  table: {
    minHeight: 330,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    padding: tokens.space.md,
    display: 'grid',
    alignContent: 'start',
    gap: tokens.space.md,
  },
  '@keyframes pulse': { '0%': { backgroundPosition: '100% 0' }, '100%': { backgroundPosition: '-100% 0' } },
})
