import { createUseStyles } from 'react-jss'
import { tokens } from '@/theme/tokens'

export const useSkeletonStyles = createUseStyles({
  pulse: {
    height: 14,
    borderRadius: tokens.radius.sm,
    background: `linear-gradient(90deg, ${tokens.color.bgMuted} 0%, ${tokens.color.border} 50%, ${tokens.color.bgMuted} 100%)`,
    backgroundSize: '200% 100%',
    animation: '$pulse 1.25s ease-in-out infinite',
  },
  width40: { width: '40%' },
  width42: { width: '42%' },
  width55: { width: '55%' },
  width68: { width: '68%' },
  width70: { width: '70%' },
  width76: { width: '76%' },
  width88: { width: '88%' },
  width92: { width: '92%' },
  width100: { width: '100%' },
  width110: { width: 110 },
  width120: { width: 120 },
  width170: { width: 170 },
  width220: { width: 220 },
  height11: { height: 11 },
  height16: { height: 16 },
  height26: { height: 26 },
  height32: { height: 32 },
  height34: { height: 34 },
  height36: { height: 36 },
  height38: { height: 38 },
  panelRoot: { display: 'grid', gap: tokens.space.md, padding: tokens.space.lg },
  panelChart: { height: 280 },
  dashboard: { display: 'grid', gap: tokens.space.lg },
  cards: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))', gap: tokens.space.md },
  card: {
    minHeight: 142,
    padding: tokens.space.md,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    display: 'grid',
    alignContent: 'start',
    gap: tokens.space.sm,
  },
  cardTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  icon: { width: 32, height: 32 },
  section: {
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    overflow: 'hidden',
  },
  sectionHead: {
    minHeight: 68,
    padding: tokens.space.lg,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: tokens.space.md,
    borderBottom: `1px solid ${tokens.color.border}`,
  },
  controlRow: { display: 'flex', gap: tokens.space.sm },
  sectionBody: {
    padding: tokens.space.lg,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.4fr) minmax(260px, .8fr)',
    gap: tokens.space.lg,
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  },
  graph: { height: 300 },
  tableRows: { display: 'grid', gap: tokens.space.sm, alignContent: 'start' },
  page: { display: 'grid', gap: tokens.space.md },
  toolbar: {
    height: 68,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    padding: tokens.space.md,
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  table: {
    minHeight: 330,
    border: `1px solid ${tokens.color.border}`,
    borderRadius: tokens.radius.md,
    background: tokens.color.bgCard,
    padding: tokens.space.md,
    display: 'grid',
    alignContent: 'start',
    gap: tokens.space.md,
  },
  '@keyframes pulse': { '0%': { backgroundPosition: '100% 0' }, '100%': { backgroundPosition: '-100% 0' } },
})
